### ISSUE TITLE
[Question] Why it is not an extension to IConnection?

### ISSUE THREAD

**Issue by kirill-lappo-dg7** [DaredevilOSS/sqlc-gen-csharp#84]
Probably, that is a stupid question, but why not generate an extension class to `IConnection` instead of query class? 

Developers might want to decide on their own how they create connections to db, it doesn't matter which db they use

**Comment by SockworkOrange** [comment]
I am not sure about using Dapper or not (I'll open a different discussion - introducing an extra dependency is something I wish to avoid, if possible).
Regarding generating the code as extension to IConnection itself - I'll add it as an option, shouldn't be too hard.
