### ISSUE TITLE
[REQUEST] Namespace option

### ISSUE THREAD

**Issue by kirill-lappo-dg7** [DaredevilOSS/sqlc-gen-csharp#85]
It would be more convenient to have a separate parameter for a namespace (just like in grpc gen).

For example, I might have project placed in `./src/Project.Repo.Queries/` and would like to have my queries be in `Project.Repo.Queries.Gen` namespace

**Comment by SockworkOrange** [comment]
you mean, a base_namespace setting like this?
https://buf.build/grpc/csharp?version=v1.67.0
Good idea, if you want you can submit a PR or I'll get to it sometime in the following weeks.

**Comment by kirill-lappo-dg7** [comment]
i guess it is the property, no idea about grpc gen internals
usually we specify it in proto file like 

```grpc
syntax = "proto3";

// so all generated classes will be placed in Company.Greeter namespace
option csharp_namespace = "Company.Greeter";

package greet;

// services and messages ...
```

**Comment by SockworkOrange** [comment]
added in latest release:)
