### ISSUE TITLE
Dapper Support

### ISSUE THREAD

**Issue by JamiroFerrara** [DaredevilOSS/sqlc-gen-csharp#89]
Dear authors,

First of all great work on this extension. 

I was looking at the generated C# code from sqlc and thought it would be great if it could be used with dapper. 

Instead of instantiating the connection and executing the query, it would just be a wrapper around the Dapper.Query() methods with types hooked in. 

Would get all the benefits of having separate sql files and type safety while offloading execution to Dapper.

**Comment by JamiroFerrara** [comment]
This would be useful because it would enable support for everything Dapper is able to use.

**Comment by SockworkOrange** [comment]
I'm opening this up for anyone who wishes to contribute. The implementation should be:
1. Provide an option whether to have the generated code use Dapper or not (default should be no)
2. It should simply be implemented as another DbDriver

The reason I want to keep the current behaviour (at least for the databases sqlc itself actually supports) is to avoid the use of extra dependencies. However, if we see people simply prefer to use Dapper, we will at least change it to the default behavior.

**Comment by doron050** [comment]
Hi, @JamiroFerrara I just finished adding dapper support for all databases
Have fun, if you have any feedback we are always here

**Comment by JamiroFerrara** [comment]
@doron050 **_Thank you_** so much!!!
